import { Brain, Workflow, BarChart3, Sparkles, ShieldCheck, Zap } from "lucide-react";
import { motion } from "framer-motion";

const features = [
  {
    icon: Brain,
    title: "AI Travel Story Generation",
    description:
      "Generate personalized and engaging travel stories using AI based on user inputs, preferences, and travel experiences.",
  },
  {
    icon: Workflow,
    title: "Story History & Management",
    description:
      "Users can view, read, and manage all previously generated travel stories while tracking their activity history.",
  },
  {
    icon: Sparkles,
    title: "Public Story Exploration",
    description:
      "Read and explore publicly shared travel stories from other users to gain inspiration and insights.",
  },
  {
    icon: BarChart3,
    title: "Admin Analytics Dashboard",
    description:
      "Admins can track total users, monitor the number of stories generated by each user, and analyze platform usage in real time.",
  },
  {
    icon: ShieldCheck,
    title: "User & Feedback Management",
    description:
      "Admins can ban or unban users, toggle user status, and manage user feedback by deleting inappropriate reviews.",
  },
  {
    icon: Zap,
    title: "AI Assistance & Support",
    description:
      "Users can interact with AI for guidance, suggestions, and help related to story creation and platform usage.",
  },
];


export default function Features() {
  return (
    <main className="bg-slate-900 text-gray-200" id="features">
      {/* Hero */}
      <section className="max-w-7xl mx-auto px-6 py-20 text-center">
        <motion.h1
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6 }}
          className="text-4xl sm:text-5xl font-bold mb-6"
        >
          Powerful Features for Smarter Journeys
        </motion.h1>
        <p className="text-gray-400 max-w-2xl mx-auto text-lg">
          Journey AI equips your team with intelligent tools to design, analyze,
          and optimize customer journeys at every touchpoint.
        </p>
      </section>

      {/* Features Grid */}
      <section className="max-w-7xl mx-auto px-6 pb-24">
        <div className="grid gap-8 sm:grid-cols-2 lg:grid-cols-3">
          {features.map((feature, index) => (
            <motion.div
              key={feature.title}
              initial={{ opacity: 0, y: 30 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.5, delay: index * 0.05 }}
              className="bg-slate-800 rounded-2xl p-6 shadow hover:shadow-lg transition"
            >
              <feature.icon className="text-sky-400 mb-4" size={28} />
              <h3 className="text-lg font-semibold mb-2">
                {feature.title}
              </h3>
              <p className="text-sm text-gray-400 leading-relaxed">
                {feature.description}
              </p>
            </motion.div>
          ))}
        </div>
      </section>

    
      
    </main>
  );
}
